import React, { useState } from 'react'
import { NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, CalendarDays, CheckCircle2, Clock3, LogIn, MessageCircle, ShieldCheck, Users, Settings, UserRound, Bot, Building2 } from 'lucide-react'
import { supabase } from './lib/supabase'

type Feature = [string, string, React.ElementType]
const items = [['/dashboard','Dashboard'],['/agenda','Agenda'],['/pacientes','Pacientes'],['/profissionais','Profissionais'],['/whatsapp','WhatsApp'],['/automacoes','Automações'],['/configuracoes','Configurações']] as const
const features: Feature[] = [['Agenda simples','Visualize seus atendimentos por dia, semana ou mês.',CalendarDays],['Pacientes organizados','Tenha dados e histórico em um só lugar.',Users],['Lembretes automáticos','Avise seus pacientes antes do atendimento.',Clock3]]

function Landing(){const navigate=useNavigate();return <div className="landing"><header className="landing-nav"><div className="logo"><b>C</b> Consulta Pro</div><button className="login-link" onClick={()=>navigate('/login')}><LogIn size={16}/> Entrar</button></header><section className="hero"><div className="hero-copy"><span className="eyebrow">GESTÃO INTELIGENTE DE ATENDIMENTOS</span><h1>Sua agenda organizada.<br/><em>Seu consultório conectado.</em></h1><p>Centralize pacientes, profissionais, agenda e lembretes de WhatsApp em um único lugar.</p><button className="hero-btn" onClick={()=>navigate('/login')}>Acessar meu consultório <ArrowRight size={17}/></button><div className="trust"><ShieldCheck size={16}/><span>Dados isolados por empresa e preparados para Supabase RLS</span></div></div><div className="hero-card"><div className="mini-top"><span>Hoje · 03 setembro</span><CheckCircle2 size={17}/></div><div className="mini-title">Próximos atendimentos</div>{[['10:45','João Silva','Dr. Carlos Mendes'],['11:30','Maria Souza','Dra. Marina Costa'],['14:00','Dr. Pedro Alves','Dr. Rafael Lima']].map(x=><div className="mini-row" key={x[0]}><strong>{x[0]}</strong><span><b>{x[1]}</b><small>{x[2]}</small></span><i>Confirmado</i></div>)}<div className="mini-wa"><MessageCircle size={18}/><span><b>6 lembretes enviados</b><small>WhatsApp conectado</small></span></div></div></section><section className="features">{features.map(([t,d,I])=><article key={t}><div>{React.createElement(I,{size:19})}</div><h3>{t}</h3><p>{d}</p></article>)}</section></div>}

function Login(){const navigate=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setError('');setLoading(true);if(!supabase){setError('Supabase não configurado.');setLoading(false);return}const {error}=await supabase.auth.signInWithPassword({email,password});if(error){setError('E-mail ou senha inválidos.');setLoading(false);return}navigate('/dashboard')}return <div className="auth"><div className="auth-card"><div className="logo center"><b>C</b> Consulta Pro</div><h1>Bem-vindo de volta</h1><p>Entre para acessar seu consultório.</p><form onSubmit={submit}><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@consultorio.com"/></label><label>Senha<input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Sua senha"/></label>{error&&<div className="form-error">{error}</div>}<button className="hero-btn full" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form><button className="back" onClick={()=>navigate('/')}>Voltar para o início</button></div></div>}

function Page({title,description,icon:Icon,children}:{title:string;description:string;icon:React.ElementType;children?:React.ReactNode}){return <div className="content"><div className="head"><div><h1>{title}</h1><p>{description}</p></div><button className="hero-btn">Novo</button></div><section className="panel" style={{minHeight:300}}><div style={{display:'grid',placeItems:'center',minHeight:250,textAlign:'center'}}><div><Icon size={42}/><h2 style={{marginTop:15}}>{title}</h2><p>{children||'Esta tela está pronta para receber os dados do Supabase.'}</p></div></div></section></div>}
function Dashboard(){return <div className="content"><div className="head"><div><h1>Bom dia, Alexandre</h1><p>Resumo do seu consultório.</p></div><button className="hero-btn">Novo atendimento</button></div><div className="metrics">{[['Consultas hoje','3'],['Confirmadas','1'],['Pendentes','2'],['Realizadas','0']].map(x=><div className="card" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="grid"><section className="panel"><h2>Próximos atendimentos</h2>{[['10:45','João Silva','Dr. Carlos Mendes'],['11:30','Maria Souza','Dra. Marina Costa'],['14:00','Pedro Alves','Dr. Rafael Lima']].map(x=><div className="row" key={x[0]}><time>{x[0]}</time><span><b>{x[1]}</b><small>{x[2]}</small></span><em>Agendado</em></div>)}</section><section className="panel"><h2>WhatsApp <i>● Conectado</i></h2><div className="wa"><MessageCircle/><span><b>+55 55 99999-0000</b><small>Instância: clinica-medica</small></span></div><div className="stats"><b>18<small>mensagens hoje</small></b><b>6<small>lembretes enviados</small></b></div></section></div></div>}
function Layout(){return <div className="layout"><aside><div className="logo"><b>C</b> Consulta Pro</div><div className="company">Clínica Médica Santiago</div><nav>{items.map(([path,label])=><NavLink key={path} to={path}>{label}</NavLink>)}</nav><div className="profile"><b>A</b><span>Alexandre<small>Administrador</small></span></div></aside><main><header><strong>Clínica Médica Santiago</strong><span>Alexandre</span></header><Routes><Route index element={<Dashboard/>}/><Route path="dashboard" element={<Dashboard/>}/><Route path="agenda" element={<Page title="Agenda" description="Organize seus atendimentos." icon={CalendarDays}/>}/><Route path="pacientes" element={<Page title="Pacientes" description="Gerencie os pacientes da empresa." icon={Users}/>}/><Route path="profissionais" element={<Page title="Profissionais" description="Gerencie os profissionais da empresa." icon={UserRound}/>}/><Route path="whatsapp" element={<Page title="WhatsApp" description="Acompanhe a integração da empresa." icon={MessageCircle}/>}/><Route path="automacoes" element={<Page title="Automações" description="Configure lembretes e mensagens automáticas." icon={Bot}/>}/><Route path="configuracoes" element={<Page title="Configurações" description="Configure empresa, usuários e preferências." icon={Settings}/>}/></Routes></main></div>}

\nexport default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="*" element={<Layout/>}/></Routes>}