import React, { useEffect, useState } from 'react'
import { Navigate, NavLink, Outlet, Route, Routes, useNavigate } from 'react-router-dom'
import { Activity, ArrowLeft, BarChart3, Bot, Building2, CalendarDays, CheckCircle2, Eye, EyeOff, LayoutDashboard, LogOut, MessageCircle, Plus, Settings, ShieldCheck, UserRound, Users } from 'lucide-react'
import { supabase } from './lib/supabase'
import { TenantProvider, useTenant } from './contexts/TenantContext'
import Landing from './Landing'

function getSupabase(){if(!supabase)throw new Error('Supabase não configurado.');return supabase}
const BR_TIMEZONE='America/Sao_Paulo'
type Company={id:string;name:string;legal_name?:string|null;cnpj?:string|null;phone?:string|null;email?:string|null;timezone?:string|null}
type Icon=React.ComponentType<any>
const tenantNav:[string,string,Icon][]=[['/dashboard','Dashboard',LayoutDashboard],['/agenda','Agenda',CalendarDays],['/pacientes','Pacientes',Users],['/profissionais','Profissionais',UserRound],['/whatsapp','WhatsApp',MessageCircle],['/automacoes','Automações',Bot],['/configuracoes','Configurações',Settings]]
const adminNav:[string,string,Icon][]=[['/admin/dashboard','Dashboard',LayoutDashboard],['/admin/empresas','Empresas',Building2],['/admin/usuarios','Usuários',Users],['/admin/permissoes','Permissões',ShieldCheck],['/admin/whatsapp','WhatsApp',MessageCircle],['/admin/mensagens','Mensagens',BarChart3],['/admin/automacoes','Automações',Bot],['/admin/atividade','Atividade',Activity],['/admin/configuracoes','Configurações',Settings]]
function Logo(){return <div className="app-logo"><img src="/favicon.svg" alt="Consulta Pro"/><span>Consulta Pro</span></div>}
function Login(){const navigate=useNavigate();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[error,setError]=useState('');const[loading,setLoading]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setError('');setLoading(true);try{const client=getSupabase();const{error}=await client.auth.signInWithPassword({email,password});if(error){setError('E-mail ou senha inválidos.');return}navigate('/dashboard')}finally{setLoading(false)}}return <div className="auth"><div className="auth-card"><Logo/><h1>Bem-vindo de volta</h1><p>Entre para acessar o sistema.</p><form onSubmit={submit}><label>E-mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<div className="password-wrap"><input type={showPassword?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" className="icon-btn" title={showPassword?'Ocultar senha':'Mostrar senha'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<div className="form-error">{error}</div>}<button className="hero-btn full" disabled={loading}>{loading?'Entrando...':'Entrar'}</button></form><button className="back" onClick={()=>navigate('/')}>Voltar para o início</button></div></div>}
function SessionGate(){const[state,setState]=useState<'loading'|'ready'|'none'>('loading');useEffect(()=>{let alive=true;async function load(){try{const client=getSupabase();const{data:{session}}=await client.auth.getSession();if(alive)setState(session?'ready':'none')}catch(error){console.error('Erro ao carregar sessão:',error);if(alive)setState('none')}}load();const client=getSupabase();const{data}=client.auth.onAuthStateChange((_event,session)=>{if(alive)setState(session?'ready':'none')});return()=>{alive=false;data.subscription.unsubscribe()}},[]);if(state==='loading')return <div className="auth"><div className="panel">Carregando sessão...</div></div>;if(state==='none')return <Navigate to="/login" replace/>;return <Outlet/>}
function RoleGate({admin}:{admin:boolean}){const[state,setState]=useState<'loading'|'allowed'|'denied'>('loading');useEffect(()=>{let alive=true;async function load(){try{if(!supabase){if(alive)setState('denied');return}const client=supabase;if(!client){if(alive)setState('denied');return}const{data:{user},error:userError}=await client.auth.getUser();if(userError||!user){if(alive)setState('denied');return}const{data:profile,error:profileError}=await client.from('profiles').select('is_superadmin').eq('id',user.id).maybeSingle();if(profileError){console.error('Erro ao carregar perfil:',profileError);if(alive)setState('denied');return}const jwtAdmin=user.app_metadata?.role==='superadmin'||user.app_metadata?.is_superadmin===true;const isAdmin=Boolean(profile?.is_superadmin||jwtAdmin);if(alive)setState(isAdmin===admin?'allowed':'denied')}catch(error){console.error('Erro ao validar acesso:',error);if(alive)setState('denied')}}load();const timer=window.setTimeout(()=>{if(alive)setState('denied')},8000);return()=>{alive=false;window.clearTimeout(timer)}},[admin]);if(state==='loading')return <div className="auth"><div className="panel">Carregando acesso...</div></div>;if(state==='denied')return <Navigate to={admin?'/dashboard':'/admin/dashboard'} replace/>;return <Outlet/>}
function AdminLayout(){const navigate=useNavigate();async function logout(){await supabase?.auth.signOut();navigate('/login')}return <div className="layout"><aside><Logo/><div className="company"><strong>Administração</strong><small>Visão global da plataforma</small></div><nav className="sidebar-nav">{adminNav.map(([path,label,Icon])=><NavLink key={path} to={path}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="profile"><b>SA</b><span>Superadmin<small>Controle global</small></span><button onClick={logout} title="Sair"><LogOut size={15}/></button></div></aside><main><header><strong>Consulta Pro</strong><span>Superadmin</span></header><Outlet/></main></div>}
function Metric({label,value,icon:Icon}:{label:string;value:string|number;icon?:Icon}){return <div className="card">{Icon&&<Icon size={17}/>}<span>{label}</span><b>{value}</b></div>}
function AdminDashboard(){const{companies}=useTenant();const[stats,setStats]=useState({messages:0,patients:0,appointments:0});useEffect(()=>{async function load(){const client=getSupabase();const count=async(table:string)=>{const r=await client.from(table).select('*',{count:'exact',head:true});return r.count||0};setStats({messages:await count('whatsapp_messages'),patients:await count('patients'),appointments:await count('appointments')})}load()},[]);return <div className="content"><div className="head"><div><h1>Visão geral</h1><p>Operação global do Consulta Pro.</p></div><NavLink className="hero-btn" to="/admin/empresas/nova"><Plus size={16}/> Nova empresa</NavLink></div><div className="metrics"><Metric label="Empresas" value={companies.length} icon={Building2}/><Metric label="Pacientes" value={stats.patients} icon={Users}/><Metric label="Atendimentos" value={stats.appointments} icon={CalendarDays}/><Metric label="Mensagens" value={stats.messages} icon={MessageCircle}/></div></div>}
function AdminCompanies(){const{companies}=useTenant();const navigate=useNavigate();return <div className="content"><div className="head"><div><h1>Empresas</h1><p>Todos os consultórios e clínicas da plataforma.</p></div><button className="hero-btn" onClick={()=>navigate('/admin/empresas/nova')}><Plus size={16}/> Nova empresa</button></div><section className="panel">{companies.length===0?<div className="empty-box"><Building2 size={35}/><h2>Nenhuma empresa cadastrada</h2><p>Crie o primeiro consultório para começar.</p><button className="hero-btn" onClick={()=>navigate('/admin/empresas/nova')}>Criar empresa</button></div>:companies.map(c=><div className="row" key={c.id}><Building2 size={18}/><span><b>{c.name}</b><small>{c.cnpj||'CNPJ não informado'}</small></span><i>Ativa</i><NavLink to={'/admin/empresas/'+c.id}>Gerenciar</NavLink></div>)}</section></div>}
function NewCompany(){const navigate=useNavigate();const{refresh}=useTenant();const[name,setName]=useState('');const[legal,setLegal]=useState('');const[cnpj,setCnpj]=useState('');const[phone,setPhone]=useState('');const[email,setEmail]=useState('');const[timezone,setTimezone]=useState(BR_TIMEZONE);const[busy,setBusy]=useState(false);const[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();const client=getSupabase();if(!name.trim())return;setBusy(true);setError('');const{error}=await client.rpc('superadmin_create_company',{company_name:name.trim(),timezone,legal_name:legal||null,cnpj:cnpj||null,phone:phone||null,email:email||null});if(error)setError(error.message);else{await refresh();navigate('/admin/empresas')}setBusy(false)}return <div className="content"><div className="head"><div><button className="back-link" onClick={()=>navigate('/admin/empresas')}><ArrowLeft size={15}/> Empresas</button><h1>Nova empresa</h1><p>Cadastre um novo tenant do Consulta Pro.</p></div></div><section className="panel"><form className="form-grid" onSubmit={submit}><label>Nome fantasia*<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Fuso horário*<select required value={timezone} onChange={e=>setTimezone(e.target.value)}><option value="America/Sao_Paulo">Brasil — Brasília (UTC−3)</option><option value="America/Manaus">Brasil — Manaus (UTC−4)</option><option value="America/Rio_Branco">Brasil — Rio Branco (UTC−5)</option><option value="America/Noronha">Brasil — Fernando de Noronha (UTC−2)</option></select><small>Usado para agenda e automações.</small></label><label>Razão social<input value={legal} onChange={e=>setLegal(e.target.value)}/></label><label>CNPJ<input value={cnpj} onChange={e=>setCnpj(e.target.value)}/></label><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>{error&&<div className="form-error">{error}</div>}<div><button className="hero-btn" disabled={busy}>{busy?'Criando...':'Criar empresa'} <CheckCircle2 size={16}/></button></div></form></section></div>}
function TenantLayout(){const{activeCompany,companies,setActiveCompany}=useTenant();const navigate=useNavigate();async function logout(){await supabase?.auth.signOut();navigate('/login')}if(!activeCompany)return <div className="content"><section className="panel"><Building2 size={36}/><h2>Nenhuma empresa vinculada</h2><p>Seu usuário ainda não possui um consultório associado.</p></section></div>;return <div className="layout"><aside><Logo/><div className="company"><strong>{activeCompany.name}</strong><small>Tenant ativo</small></div>{companies.length>1&&<select className="company-select" value={activeCompany.id} onChange={e=>{const c=companies.find(x=>x.id===e.target.value);if(c)setActiveCompany(c)}}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}<nav className="sidebar-nav">{tenantNav.map(([path,label,Icon])=><NavLink key={path} to={path}><Icon size={18}/><span>{label}</span></NavLink>)}</nav><div className="profile"><b>U</b><span>Conta<small>Tenant protegido por RLS</small></span><button onClick={logout}><LogOut size={15}/></button></div></aside><main><header><strong>{activeCompany.name}</strong><span>Operação</span></header><Outlet/></main></div>}
export default function App(){return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route element={<SessionGate/>}><Route element={<TenantProvider><Outlet/></TenantProvider>}><Route element={<RoleGate admin={true}/>}><Route element={<AdminLayout/>}><Route path="admin/dashboard" element={<AdminDashboard/>}/><Route path="admin/empresas" element={<AdminCompanies/>}/><Route path="admin/empresas/nova" element={<NewCompany/>}/></Route></Route><Route element={<RoleGate admin={false}/>}><Route element={<TenantLayout/>}><Route index element={<Navigate to="/dashboard" replace/>}/></Route></Route></Route></Route><Route path="*" element={<Navigate to="/" replace/>}/></Routes>}
